# Generated by Django 4.2.5 on 2023-10-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriacompra',
            fields=[
                ('idcatcompra', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(blank=True, max_length=20, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('esactivo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoriacompra',
            },
        ),
        migrations.CreateModel(
            name='Categoriaproducto',
            fields=[
                ('idcatproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecatproducto', models.CharField(blank=True, max_length=30, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoriaproducto',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecompra', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tipopago', models.BooleanField(blank=True, null=True)),
                ('fechacompra', models.DateTimeField(blank=True, null=True)),
                ('idcatcompra', models.ForeignKey(blank=True, db_column='idcatcompra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras_inventario.categoriacompra')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('nombreproveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.TextField(blank=True, null=True)),
                ('preciocompra', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('precioventa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idcatproducto', models.ForeignKey(blank=True, db_column='idcatproducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras_inventario.categoriaproducto')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('iddetcompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fechadetcompra', models.DateTimeField(blank=True, null=True)),
                ('idcompra', models.ForeignKey(blank=True, db_column='idcompra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras_inventario.compras')),
                ('idproducto', models.ForeignKey(blank=True, db_column='idproducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras_inventario.productos')),
            ],
            options={
                'db_table': 'detallecompra',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='idproveedor',
            field=models.ForeignKey(blank=True, db_column='idproveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras_inventario.proveedor'),
        ),
    ]
