# Generated by Django 4.2.5 on 2023-10-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacompra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='compras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True},
        ),
    ]
