# Generated by Django 4.2.5 on 2023-10-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras_inventario', '0001_initial'),
        ('login', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(blank=True, max_length=50, null=True)),
                ('idpersonal', models.ForeignKey(blank=True, db_column='idpersonal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.personal')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('precioventa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('esactivo', models.BooleanField(blank=True, null=True)),
                ('fechaventa', models.DateTimeField(blank=True, null=True)),
                ('idcliente', models.ForeignKey(blank=True, db_column='idcliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('idmesa', models.AutoField(primary_key=True, serialize=False)),
                ('numeromesa', models.IntegerField(blank=True, null=True)),
                ('esactivo', models.BooleanField(blank=True, null=True)),
                ('idcliente', models.ForeignKey(blank=True, db_column='idcliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.clientes')),
                ('idpersonal', models.ForeignKey(blank=True, db_column='idpersonal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.personal')),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('iddetventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fechaventa', models.DateTimeField(blank=True, null=True)),
                ('esactivo', models.BooleanField(blank=True, null=True)),
                ('idproducto', models.ForeignKey(blank=True, db_column='idproducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras_inventario.productos')),
                ('idventa', models.ForeignKey(blank=True, db_column='idventa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.venta')),
            ],
            options={
                'db_table': 'detalleventa',
            },
        ),
    ]
