# Generated by Django 4.2.5 on 2023-10-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mesas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': True},
        ),
    ]
