# Generated by Django 4.2.5 on 2023-09-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
