# Generated by Django 4.2.5 on 2023-10-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(blank=True, max_length=25, null=True)),
                ('esactivo', models.BooleanField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('idpersonal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.TextField(blank=True, null=True)),
                ('clave', models.TextField(blank=True, null=True)),
                ('esactivo', models.BooleanField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idrol', models.ForeignKey(blank=True, db_column='idrol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.rol')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
    ]
