# Generated by Django 4.2.5 on 2023-10-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
    ]
