# Generated by Django 4.2.5 on 2023-10-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idmenu', models.AutoField(primary_key=True, serialize=False)),
                ('nombremenu', models.CharField(blank=True, max_length=30, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Menurol',
            fields=[
                ('idmenurol', models.AutoField(primary_key=True, serialize=False)),
                ('idmenu', models.ForeignKey(blank=True, db_column='idmenu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menu')),
                ('idrol', models.ForeignKey(blank=True, db_column='idrol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.rol')),
            ],
            options={
                'db_table': 'menurol',
            },
        ),
    ]
