# Generated by Django 4.2.5 on 2023-10-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menurol',
            options={'managed': True},
        ),
    ]
